# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballegro', '0002_auto_20170325_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField(blank=True)),
                ('add_team_to_phrase', models.BooleanField()),
            ],
        ),
    ]
