# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballegro', '0004_auto_20170325_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='id',
        ),
        migrations.AddField(
            model_name='clothes',
            name='url_name',
            field=models.TextField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
